version: '3.7'

volumes:
  django_storage:

services:
  web:
    build: ./django_main
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - django_storage:/usr/src/app/django_main
    ports:
      - 8000:8080
    env_file:
      - ./.env.dev

